# Multi-stage build for building Next.js frontend
# FROM node:14 AS frontend-builder
FROM node:20.9.0 AS frontend-builder

WORKDIR /app/frontend
# WORKDIR /var/www/html/strii-frontend

RUN apt-get update \
  && apt-get -y install git libicu-dev libonig-dev libzip-dev zip unzip locales vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && locale-gen en_US.UTF-8 \
  && localedef -f UTF-8 -i en_US en_US.UTF-8

ENV \
  TZ=Asia/Tokyo \
  LANG=en_US.UTF-8 \
  LANGUAGE=en_US:en \
  LC_ALL=en_US.UTF-8 

# COPY frontend/package*.json ./
COPY strii-frontend/package*.json ./
RUN npm install

COPY strii-frontend/ ./

RUN npm run build

#### Laravel backend
FROM php:8.2-apache AS backend-builder

WORKDIR /var/www/html/strii-backend

# Install dependencies
RUN apt-get update \
  && apt-get -y install git libicu-dev libonig-dev libzip-dev unzip locales vim zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && locale-gen en_US.UTF-8 \
  && localedef -f UTF-8 -i en_US en_US.UTF-8 \
  && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
  && docker-php-ext-install intl pdo_mysql zip bcmath gd exif \
  # composer config -g process-timeout 3600 && \
  # composer config -g repos.packagist composer https://packagist.org
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && a2enmod rewrite



ENV \
  LANG=en_US.UTF-8 \
  LANGUAGE=en_US:en \
  LC_ALL=en_US.UTF-8 

COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

COPY strii-backend/composer.* ./

COPY strii-backend/ ./
COPY php.ini /usr/local/etc/php/php.ini

RUN composer install --no-dev --optimize-autoloader
RUN php artisan key:generate
# RUN php artisan config:cache
RUN php artisan storage:link

# publicフォルダとstorageフォルダのパーミッションを設定
RUN chown -R www-data:www-data /var/www/html/strii-backend/public /var/www/html/strii-backend/storage
RUN chmod -R 775 /var/www/html/strii-backend/public /var/www/html/strii-backend/storage

#### Apache configuration
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules
RUN a2enmod rewrite

# フロントエンドのビルドをApacheに統合
COPY --from=frontend-builder /app/frontend/ /var/www/html/strii-frontend

# ベースイメージのnodeをコピーしてインストール
COPY --from=node:20.9.0 /usr/local/bin/node /usr/local/bin/node
COPY --from=node:20.9.0 /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs \
 && ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
 && ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npx
# ENTRYPOINT [ "sh", "-cx" ]

RUN chown -R www-data:www-data /var/www/html/strii-frontend/.next
RUN chmod -R 775 /var/www/html/strii-frontend/.next

EXPOSE 80


CMD ["/bin/sh", "-c", "apache2-foreground"]
